-- FarmTech Solutions - Cap 1
-- Estrutura Oracle esperada para leituras recebidas do Wokwi via API.

CREATE TABLE FARMTECH_SENSOR_READINGS (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    device_id VARCHAR2(80) NOT NULL,
    cultura VARCHAR2(40) NOT NULL,
    umidade_percent NUMBER(5, 2) NOT NULL,
    temperatura_c NUMBER(5, 2) NOT NULL,
    ph NUMBER(4, 2) NOT NULL,
    n_presente NUMBER(1) DEFAULT 0 NOT NULL,
    p_presente NUMBER(1) DEFAULT 0 NOT NULL,
    k_presente NUMBER(1) DEFAULT 0 NOT NULL,
    limiar_umidade_percent NUMBER(5, 2) NOT NULL,
    bomba_ligada NUMBER(1) DEFAULT 0 NOT NULL,
    CONSTRAINT chk_farmtech_n CHECK (n_presente IN (0, 1)),
    CONSTRAINT chk_farmtech_p CHECK (p_presente IN (0, 1)),
    CONSTRAINT chk_farmtech_k CHECK (k_presente IN (0, 1)),
    CONSTRAINT chk_farmtech_bomba CHECK (bomba_ligada IN (0, 1)),
    CONSTRAINT chk_farmtech_ph CHECK (ph BETWEEN 0 AND 14)
);

CREATE INDEX IDX_FARMTECH_SENSOR_CREATED
    ON FARMTECH_SENSOR_READINGS (created_at DESC);

CREATE INDEX IDX_FARMTECH_SENSOR_CULTURA
    ON FARMTECH_SENSOR_READINGS (cultura);

-- Insercao manual para teste inicial no SQL Developer.
INSERT INTO FARMTECH_SENSOR_READINGS (
    device_id,
    cultura,
    umidade_percent,
    temperatura_c,
    ph,
    n_presente,
    p_presente,
    k_presente,
    limiar_umidade_percent,
    bomba_ligada
) VALUES (
    'manual-sql',
    'soja',
    62.50,
    26.40,
    6.35,
    1,
    1,
    0,
    55.00,
    0
);

COMMIT;

-- Consulta exigida como evidencia basica.
SELECT *
FROM FARMTECH_SENSOR_READINGS
ORDER BY created_at DESC;

-- Ultimas 10 leituras.
SELECT *
FROM FARMTECH_SENSOR_READINGS
ORDER BY created_at DESC
FETCH FIRST 10 ROWS ONLY;

-- Resumo por cultura.
SELECT
    cultura,
    COUNT(*) AS total_leituras,
    ROUND(AVG(umidade_percent), 2) AS umidade_media,
    ROUND(AVG(temperatura_c), 2) AS temperatura_media,
    ROUND(AVG(ph), 2) AS ph_medio,
    SUM(bomba_ligada) AS acionamentos_bomba
FROM FARMTECH_SENSOR_READINGS
GROUP BY cultura
ORDER BY cultura;

-- Leituras em que a bomba deveria atuar por baixa umidade.
SELECT
    id,
    created_at,
    cultura,
    umidade_percent,
    limiar_umidade_percent,
    bomba_ligada
FROM FARMTECH_SENSOR_READINGS
WHERE umidade_percent < limiar_umidade_percent
ORDER BY created_at DESC;
